### ISSUE TITLE
Crashing on Windows

### ISSUE THREAD

**Issue by Verox-** [KoffeinFlummi/armake#1]
paa2img crashes on windows (paa2img.c:422). I'm assuming it's an out-of-bounds error as it is reported the Width to be >32000 where it should be 512. 

Strangely, it doesn't crash with small 8x8 paa files.

**Comment by Verox-** [comment]
Interesting point, running on Linux it detectes the PAAs as having LZO compression, and converts them properly whereas under Windows it detects them as having no compression.

**Comment by MarcBook** [comment]
**Visual Studio Debugger:**
`Ausnahmefehler bei 0x76918680 (msvcrt.dll) in armake.exe: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x024FDFFC`

**Comment by MarcBook** [comment]
http://pastebin.com/zZXP3dyQ
