### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Killswitch00** [KoffeinFlummi/armake#14]
Platform: GNU/Linux

Leaks detected by valgrind:
- in preprocess.c, the `malloc()` calls for `constants[2].value` and `constants[3].value` will re-alloc a 1 byte memory slice for each recursive call of `preprocess()`. The memory allocated by the parent invocation of preprocess() is lost.
- in filesystem.c, the `traverse_directory_recursive()` calls `scandir()` which allocates memory in the `namelist` array. This memory is not entirely freed if the calls to `traverse_directory_recursive()` or `callback()` returns a non-zero result .

Not a leak, but a bug: in `filesystem.c` , the array `containing` is created like this:

```
char containing[strlen(target)];
```

Later on, this operation is made:

```
strcpy(containing, target);
```

Problem: the terminating zero byte from the source string will not fit into the destination.
Solution: `char containing[strlen(target) + 1];`

**Comment by KoffeinFlummi** [comment]
Thanks for the report! :+1:
