### ISSUE TITLE
Building with OSX

### ISSUE THREAD

**Issue by AACO** [KoffeinFlummi/armake#19]
Hey Koffein, not exactly sure where to post this, but I was able to get the armake tool working in OSX with some slight modifications.
1. I had to convert the soft tabs in the Makefiles to actual tabs (I assume it's just a git auto conversion issue)
2. I had to add `-I/usr/local/opt/openssl/include` to the CLIBS arguments
3. I had to change the install locations to `/usr/local` instead of just `/usr`

```
    mkdir -p $(DESTDIR)/usr/local/bin
    mkdir -p $(DESTDIR)/usr/local/share/bash-completion/completions
    mkdir -p $(DESTDIR)/etc/bash_completion.d
    install -m 0755 $(BIN)/armake $(DESTDIR)/usr/local/bin
    install -m 0644 completions/armake $(DESTDIR)/usr/local/share/bash-completion/completions
    install -m 0644 completions/armake $(DESTDIR)/etc/bash_completion.d
```

El Capitan's [System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection)  causes a lot of issues with just `/usr` :(

**Comment by jonpas** [comment]
> I had to convert the soft tabs in the Makefiles to actual tabs (I assume it's just a git auto conversion issue)

No, https://github.com/KoffeinFlummi/armake/blob/master/Makefile#L1 allows to use soft tabs. Not sure in which `make` this was added, I know it's not part of official Ubuntu repositories yet, probably same for OS X.

**Comment by AACO** [comment]
Ahh, yeah I'm running Make 3.81 (looks like the feature was added in Make 3.82, such is life)

```
make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

I mainly wanted to share my experience so if any other dev is running OSX they have simple instructions, instead of stumbling through the process, like myself.

**Comment by jonpas** [comment]
Was this not done already? Travis is building on OSX apparently.
6a05a9145a400331ea41984b44fecaafc404be1d

**Comment by Dahlgren** [comment]
I've created a formula for homebrew but a lot has changed since 0.5.1. Requirements such as bison has been added. I think it's better to wait with submission it until a new release is published.

https://github.com/Dahlgren/homebrew-core/commit/89d2e71b971c0f5f4e0721c17d63fdaafbd64d06
