### ISSUE TITLE
redefinition-wo-undef false positive

### ISSUE THREAD

**Issue by jonpas** [KoffeinFlummi/armake#25]
`warning: Constant "QEFUNC" is being redefined without an #undef in line 16. [redefinition-wo-undef]`
is thrown for [ACE3's `script_macros.hpp` line 16](https://github.com/acemod/ACE3/blob/master/addons/main/script_macros.hpp#L16), however that define is undefined on line 14.

This is on another project that includes ACE3's `script_macros.hpp`, not tested on ACE3 itself, however both `#undef` and `#define` happen in ACE3's file.

**Comment by dedmen** [comment]
I think the constant Name includes the `(var1,var2)` meaning it would need `#undef QEFUNC(var1,var2)`
Which is reasonable if armake supports same names with different argcount.
