### ISSUE TITLE
Warnings don't show folder/pbo name and/or line number

### ISSUE THREAD

**Issue by bux** [KoffeinFlummi/armake#36]
v0.5.1

When building multiple folders with a script like:

```sh
#!/bin/sh
for d in */; do
    target=${d%/};
    armake build $d $target.pbo;
done
```

The warnings aren't clear enough on which folder/pbo is affected.

![image](https://cloud.githubusercontent.com/assets/1235520/23015018/9946b160-f431-11e6-813b-4b995de40c29.png)

**Comment by BaerMitUmlaut** [comment]
Imo this is more an issue of the script, not armake. Armake only supports building one PBO per process, so mentioning which one caused an error/warning is rather redundant.

**Comment by bux** [comment]
I'm happy for you that you only ever had to build one PBO at time :P

When working with multiple people on multiple repos it's tremendously helpful to get proper error/warning messages on a CI build.

Sure, I could work around that with e.g. echoing the path. But that's a work around, imo.

Secondly, no line / column numbers.

**Comment by BaerMitUmlaut** [comment]
I agree that it's needed, but I don't see how that's armake's responsibility (and you didn't explain why either). Here's your fix:
```sh
#!/bin/sh
for d in */; do
    target=${d%/};
    armake build $d $target.pbo || echo "  in $target"
done
```
Line and column numbers would be great.

**Comment by KoffeinFlummi** [comment]
File name and line number are now printed along with rapification warnings. The identification of the armake instance should happen on a higher level though, like @BaerMitUmlaut said.
