### ISSUE TITLE
Crash on windows when unpacking

### ISSUE THREAD

**Issue by freghar** [KoffeinFlummi/armake#38]
Whenever I try to
```
armake_x64.exe unpack test.pbo somedir
```
the armake process crashes with a "The process has stopped working" dialog. The same happens for the 32bit binary as well. Here, `test.pbo` was created with `build`, but the crash happens on any pbo created by other tools as well (cpbo / PBO manager / BI tools). Running as administrator has no effect.

According to the library trace, https://pastebin.com/w28LuPV7, it seems to crash during or just after processing arguments, though that's where my windows debugging experience ends.

Is there any library that I could be missing, specifically needed by unpack? Any other ideas?

I'm running Windows 10 Pro (x64), in Czech mutation. Using version 0.5.1.

Thanks.

**Comment by jonpas** [comment]
Seems to work fine on current master.
