### ISSUE TITLE
Macros with suffixes in arrays fail to binarize

### ISSUE THREAD

**Issue by BaerMitUmlaut** [KoffeinFlummi/armake#39]
Armake fails to binarize arrays that contains two macros, with the first one occuring being named like the second one, but with an additional suffix.

Repro:
```cpp
#define MACRO   ""
#define MACRO_X ""
arr1[] = {MACRO, MACRO_X}; // works
arr2[] = {MACRO_X, MACRO}; // fails
```

**Comment by KoffeinFlummi** [comment]
Fixed in #47.
