### ISSUE TITLE
Arch linux build error

### ISSUE THREAD

**Issue by sekkis** [KoffeinFlummi/armake#40]
Installing armake 0.5-1 from the AUR outputs  

```
.
.
.
  CC  src/keygen.c
src/keygen.c: In function ‘generate_keypair’:
src/keygen.c:115:27: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
     custom_bn2lebinpad(rsa->n, buffer, length / 8);
                           ^~
make: *** [Makefile:25: src/keygen.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build armake package(s)
```

**Comment by jonpas** [comment]
Confirmed, same error on my Arch. And I may even know why it's happening, AUR recently updated OpenSSL to a new version, which caused issues with a bunch of packages the first day, most likely a similar issue?

**Comment by jonpas** [comment]
OpenSSL 1.1 introduced that change: https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes#Compatibility_Layer

**Comment by busquetsaguilopau** [comment]
same error here
