### ISSUE TITLE
Add support for PboPrefix.txt

### ISSUE THREAD

**Issue by tupolov** [KoffeinFlummi/armake#43]
For those mods that have used PboPrefix.txt for Mikero tool purposes, would be useful for armake to support this as well as $PBOPREFIX$ files.

**Comment by dedmen** [comment]
Would also like a way to add more properties than just the prefix one. For example version.
Maybe just a start-parameter to add a property or a different textfile in ini-like format.

**Comment by BaerMitUmlaut** [comment]
What other properties would a PBO have? I don't like the idea of having a special file.

**Comment by dedmen** [comment]
You can set any property you want. BI pbos usually have `prefix` and `version` and Mikero has his infamous `obfuscated`

**Comment by jonpas** [comment]
#65 adds additional properties via CLI, eg.: `-e version=foo`.

**Comment by jonpas** [comment]
With #65 (using above mentioned additional property) you can simply use `-e prefix=$(head -c -1 PboPrefix.txt)` and have whatever file you want (changing `-1` depending on encoding to strip away newlines at the end).

This should address both original issue by @tupolov and additional properties by @dedmen. Let me know if that is true.

**Comment by jonpas** [comment]
Assuming above is good since there were no other replies. :)

@KoffeinFlummi close!
