### ISSUE TITLE
`build` command does not support XFS filesystems

### ISSUE THREAD

**Issue by lastmikoi** [KoffeinFlummi/armake#49]
Hi there,

After a fair share of debugging and troubleshooting while trying to build a `.pbo` on my Archlinux machine, I've figured out that armake, at least in its `build` command, does not support XFS filesystems.

Indeed, on a XFS filesystem a given `dirent`'s `d_type` attribute is always set to `0`, thus making the `traverse_directory_recursive` a noop.

I'm currently working around this issue by doing everything in my `/tmp` directory which is not using XFS, but this might prove difficult for users of CentOS/RHEL 7 and higher to use armake.

**Comment by freghar** [comment]
As a sidenote, the POSIX way of doing that is `S_ISDIR(m)` from `stat(2)` (or `fstat`), `struct dirent -> d_type` is not reliable.

**Comment by KoffeinFlummi** [comment]
Does this work for you: https://github.com/KoffeinFlummi/armake/pull/50 ?

**Comment by lastmikoi** [comment]
#50 indeed seems to do the trick !

**Comment by lastmikoi** [comment]
Thanks a lot for the quick fix ! I'm happily reporting that we've now pushed usage of `armake` into production in the community I'm part of by using it to build our addons through travis.ci, it works flawlessly.
