### ISSUE TITLE
delete keyword

### ISSUE THREAD

**Issue by pixlcrashr** [KoffeinFlummi/armake#72]
The binarisation parser throws an error on the keyword `delete`. But in ArmA 3 configurations there is no such keyword `delete`.

This keyword needs to be removed.

**Comment by brainslush** [comment]
You mean Arma configs? This keyword exists. You can use it to delete classes.

**Comment by pixlcrashr** [comment]
@brainslush Alright then. I agree with you.
But nonetheless this "keyword" is usable as classname declaration and is in general no error.

**Comment by KoffeinFlummi** [comment]
Using keywords as classnames is not going to be supported and is probably not a good idea regardless.
