### ISSUE TITLE
Signature after signing is wrong

### ISSUE THREAD

**Issue by pixlcrashr** [KoffeinFlummi/armake#73]
Recently I was signing some `.pbo` files and I discovered some signing errors. Means:
If I create a signature with the BI tools, the result is different to what armake produces.
I compared file hashes to make sure that the files are different at all. Although, comparing those files in a Hex-Editor is also a valid solution to discover the error.
The problematic Parts are the last `128 + 4 + 128 Bytes` of a `.bisign` file.

The interesting thing is that I only can not sign files which contain `.bin` files. But this has to work.

`a3lib.py` produces also the same results - same signature hash.

**Comment by Braini01** [comment]
Is a3lib.py producing the BI tools result or the armake result? Can you also provide or name a pbo where this happens?

**Comment by pixlcrashr** [comment]
@Braini01 Just simply use the "all-known" `dbo_old_bike.pbo` [dbo_old_bike.zip](https://github.com/KoffeinFlummi/armake/files/1968462/dbo_old_bike.zip) for example.

a3lib.py is producing the armake result(s).

**Comment by pixlcrashr** [comment]
[community-signing.zip](https://github.com/KoffeinFlummi/armake/files/1975649/community-signing.zip)

I just added an example signature of the `dbo_old_bike.pbo` file. Moreover, @4d4a5852  4d4a5852/a3lib.py#1 is not fixing the problem (included in the test files).

**Comment by 4d4a5852** [comment]
@TheMysteriousVincent ok, that's strange - I just downloaded the zip and executed `python3 a3lib@namehash_fix.py sign testKey.biprivatekey dbo_old_bike.pbo`on linux and the created bisign had the same content as `bi.testKey.bisign` - tested it in a VM running win10, too

**Comment by pixlcrashr** [comment]
@4d4a5852 Yes, you are right. The fix is working correctly. I'm a bit tired, so I'm sorry that I executed `a3lib@master.py` instead of `a3lib@namehash_fix.py`.
But hey, you did it!

**Comment by pixlcrashr** [comment]
As @4d4a5852 solution works at all, I'll try to fix this issue @KoffeinFlummi .

**Comment by BrettMayson** [comment]
Can we expect a build anytime soon with this fix included? This is the issue preventing me from using armake, and it has been fixed already.
