### ISSUE TITLE
error: Failed to create temp folder.

### ISSUE THREAD

**Issue by JasperRab** [KoffeinFlummi/armake#76]
I'm getting these error's randomly for my addons.

https://gist.github.com/JasperRab/98e505387092b735d418bd149e0bf909

In the run above only addon main and russians are finalised the other ones are not done and pbo's aren't build for them. Also it's not always the same addon that has the error, sometimes they work all pretty rare tough, most of the time one gives the error.

Running it on windows with the following batch file.

https://gist.github.com/JasperRab/3e3a010c145e7a7f714f7b4c9f4a1beb

Is this something with windows or something with my shitty batch scripting 😛 or something with armake?

Thanks.

**Comment by KoffeinFlummi** [comment]
Fixed in 6b53295e6bbe9b7f52184e55ef01f0d7d0c79201
