### ISSUE TITLE
unpack does not work properly on win10

### ISSUE THREAD

**Issue by AndreasBrostrom** [KoffeinFlummi/armake#77]
Unpacking a pbo don't work properly on windows 10.
The only thing that is happening is that a `$PBOPREFIX$` file is created and written to all files seams to be mashed in there.

**Requirements:**
- Windows 10
- armake  (v0.6.3)

**Step to reproduce:**
- `armake unpack -f path/to/pbo path/to/unpackFolder`
- Check the unpack folder

**Comment by KoffeinFlummi** [comment]
Fixed in cbe66a3ef0af938209d3cc8342d29a029c53e593.
