### ISSUE TITLE
error: Unknown class entry type 69.

### ISSUE THREAD

**Issue by dedmen** [KoffeinFlummi/armake#82]
I don't know what this is. Maybe some type of obfuscation?

[config (2).zip](https://github.com/KoffeinFlummi/armake/files/2216901/config.2.zip)

Mikeros DeRap and BI's CfgConvert both fail. But report that the `raP` at the start was unexpected which is ofcause bullshit on a binarized file.

**Comment by 4d4a5852** [comment]
It's just broken - someone probably tried to remove some addon dependency.

The "addons[]" array was missing 16 byes - i.e. a string with 14 chars + \0.
And the class body of "AddonsMetaData" >> "List" >> "Item50" was missing completely (79 bytes).

I've filled both with some 'xxxx' data - BI's CfgConvert accepts it:

[config_fixed.zip](https://github.com/KoffeinFlummi/armake/files/2217193/config_fixed.zip)

**Comment by dedmen** [comment]
Idiots doing stuff they don't understand and then wondering why it doesn't work :man_facepalming: 
Well. The guy on BIF thanks you for the help.
