### ISSUE TITLE
tools/armake: error while loading shared libraries: libcrypto.so.1.1:

### ISSUE THREAD

**Issue by xetra11** [KoffeinFlummi/armake#97]
Hey there!

I am trying to use `armake` in my TeamCity Build Step. When running `armake` the following error is prompted:

`tools/armake: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

When I run armake on my Arch Linux or Windownz it works fine. My TeamCity is running on an ubuntu container. Is this `armake` related or TeamCity? Just need a rough outline here.

EDIT: I installed the `openssh-server` package since I saw the lib refers to that. But that did not helped either

**Comment by dedmen** [comment]
The server that you are using doesn't have the required library installed. 
Should be `libssl` package

**Comment by xetra11** [comment]
checking

**Comment by xetra11** [comment]
Well it seems to be installed but I think it is a problem with my CI environment somehow - I think I have to create links to those .o files for armake.

**Comment by Fusselwurm** [comment]
(had the same problem using armake on Travis… i think i gave up and reverted to an older version of armake)

**Comment by xetra11** [comment]
@Fusselwurm 
I found something were people are linking the libs: https://serverfault.com/questions/818445/error-while-loading-shared-libraries-libcrypto-so-1-1

Gonna try that. What armake version did you roll back to?

**Comment by McDiod** [comment]
Answering for @Fusselwurm : Pretty sure we went back to 0.5.1.

Please share if you find a solution for 0.6.x

**Comment by xetra11** [comment]
I actually just linked the `libcrypto.so.1.1` file to /user/local/lib for my case and it worked.

Found the solution through this: https://serverfault.com/questions/818445/error-while-loading-shared-libraries-libcrypto-so-1-1
